Repository xyeras/react-team-alkali, pull requests merged in 2021-04, with the labels that each got.

#11 utilized web app routing using react-router-dom
  src/App.js
  src/components/Navbar.js
  src/pages/AddMember.js
  src/pages/Dashboard.js
  src/pages/Member.js
  src/pages/Members.js
  src/routers/AppRouter.js
  touch
Labels: enhancement

#26 feat(Member.js): Create page where clicking on View Details on card leads you to the profile of intended member
  src/components/MemberList.js
  src/components/Navbar.js
  src/pages/AddMember.js
  src/pages/Member.js
  src/routers/AppRouter.js
Labels: bug, done, enhancement

#33 Eg 20 remove fluff code
  src/App.css
  src/components/MemberCard.js
  src/components/MemberList.js
  src/pages/AddMember.js
  src/pages/Dashboard.js
  src/pages/Member.js
  src/pages/Members.js
  src/routers/AppRouter.js
Labels: done, enhancement

#34 finalized all pages and css
  src/App.css
  src/components/MemberCard.js
  src/pages/AddMember.js
  src/pages/Dashboard.js
  src/pages/Member.js
  src/video/bgvid5.mp4
Labels: done
